apiVersion: v1
kind: Service
metadata:
  name: system-service
  labels:
    app: sample-api
    msservice: system
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: sample-api
    msservice: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: sample-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: system-container
          image: deadlychambers/soinshane-k8s-system
          ports:
            - containerPort: 8080
              hostIP:
          resources:
            limits:
              memory: 256Mi
              cpu: "0.2"
            requests:
              memory: 256Mi
              cpu: "0.2"
