apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-deployments
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["deployments","pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-deployments
rules:
  - apiGroups: [""]
    resources: ["deployments","pods"]
    verbs: ["get","list"]
