apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shanejava
  namespace: dev 
subjects:
  - kind: User
    name: shanejava
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shanejava
  namespace: prd
subjects:
  - kind: User
    name: shanejava
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
